### ISSUE TITLE
Please remove Nova from the list of "your" projects

### ISSUE THREAD

**Issue by TheNicolasDeveloper** [CiroZDP/cirozdp#1]
The project is not yours. You did not contribute or help at all.

I want to kindly ask you to remove it.

Thank you.

**Comment by CiroZDP** [comment]
okay

**Comment by CiroZDP** [comment]
btw stop stalking me, is disturbing to have an entire orphan asking for me bruh. i didn't meant that type of popularity

**Comment by TheNicolasDeveloper** [comment]
I am not an orphan. You are one.

**Comment by CiroZDP** [comment]
talking is free, demonstrations aren't
